[project]
name = "offlinerl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "freeingtruth", email = "freeingtruth13@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "importlib-resources>=7.0.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "onnx>=1.21.0",
    "onnxruntime>=1.24.4",
    "onnxscript>=0.6.2",
    "tensorflow>=2.21.0",
    "tensorflow-datasets>=4.9.9",
    "torch==2.10.0",
    "torchvision==0.25.0",
    "tqdm>=4.67.3",
]

[tool.maturin]
module-name = "offlinerl._core"
python-packages = ["offlinerl"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
